#!/usr/bin/env bash

export PATH=/usr/local/openresty-debug/nginx/sbin:$PATH
bucket=$1
#exec prove "$@"
prove -v ./t/000-createbucket.t :: --bucket $1
sleep 2
prove -q ./t/001-delobj.t :: --bucket $1 --object $2

prove -q ./t/003-listbuckets.t  
prove -q ./t/004-listbucket.t :: -bucket $1
prove -q ./t/005-bucketlocation.t :: --bucket $1
prove -q ./t/008-bucketop.t :: --bucket $1
prove -q ./t/009-MD5.t :: --bucket $1 --object $2
# multipart
#todo resulst output to file or ?
