#!/usr/bin/env bash

export PATH=/usr/local/openresty-debug/nginx/sbin:$PATH
bucket=$1
#exec prove "$@"
prove -q ./t/000-createbucket.t :: --bucket $1
sleep 2
prove -q ./t/001-delobj.t :: --bucket $1 --object $2

prove -q ./t/003-listbuckets.t  
prove -q ./t/004-listbucket.t :: -bucket $1
prove -q ./t/005-bucketlocation.t :: --bucket $1
# see md5 
#prove -q ./t/006-putobj.t :: --bucket $1 --object $2
#prove -q ./t/007-readobj.t :: --bucket $1 --object $2
prove -q ./t/008-bucketop.t :: --bucket $1
prove -q ./t/009-MD5.t :: --bucket $1 --object $2

# multipart
prove -q ./t/010-multiupload/010-multiinit.t :: --bucket $1 --object 10$2
prove -q ./t/010-multiupload/010-uppart.t :: --bucket $1 --object 10$2
# comp multi
#todo resulst output to file or ?
prove -q ./t/s3vroot.t
