#!/bin/sh
set -e

if [ -f /etc/debian_version ]; then
    for package in python-pip python-virtualenv python-dev libevent-dev libxml2-dev libxslt-dev zlib1g-dev; do
        if [ "$(dpkg --status -- $package 2>/dev/null|sed -n 's/^Status: //p')" != "install ok installed" ]; then
            # add a space after old values
            missing="${missing:+$missing }$package"
        fi
    done
    if [ -n "$missing" ]; then
        echo "$0: missing required DEB packages. Installing via sudo." 1>&2
        sudo apt-get -y install $missing
    fi
fi
if [ -f /etc/redhat-release ]; then
    for package in python-pip python-virtualenv python-devel libevent-devel libxml2-devel libxslt-devel zlib-devel; do
        if [ "$(rpm -qa $package 2>/dev/null)" == "" ]; then
            missing="${missing:+$missing }$package"
        fi
    done
    if [ -n "$missing" ]; then
        echo "$0: missing required RPM packages. Installing via sudo." 1>&2
        sudo yum -y install $missing
    fi
fi

virtualenv --no-site-packages --distribute virtualenv

# avoid pip bugs
./virtualenv/bin/pip install --upgrade pip

# work-around change in pip 1.5
#./virtualenv/bin/pip install setuptools --no-use-wheel --upgrade
./virtualenv/bin/pip install setuptools --no-binary --upgrade

./virtualenv/bin/pip install nose-html-reporting
#Yuanguo: I replaced "--no-use-wheel" with "--no-binary", in order to solve an issue like this: 
#    DEPRECATION: --no-use-wheel is deprecated and will be removed in the future.  Please use --no-binary :all: instead.
#    Collecting setuptools
#      Using cached setuptools-35.0.1.zip
#        Complete output from command python setup.py egg_info:
#        Traceback (most recent call last):
#          File "<string>", line 1, in <module>
#          File "setuptools/__init__.py", line 10, in <module>
#            from six.moves import filter, map
#        ImportError: No module named six.moves
#    
#        ----------------------------------------
#    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QM79aD/setuptools/

./virtualenv/bin/pip install -r requirements.txt

# forbid setuptools from using the network because it'll try to use
# easy_install, and we really wanted pip; next line will fail if pip
# requirements.txt does not match setup.py requirements -- sucky but
# good enough for now
./virtualenv/bin/python setup.py develop
